# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-24 02:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_post_marquee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quote',
            new_name='marq',
        ),
    ]
