# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-24 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_marq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='marq',
        ),
    ]
