# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-02 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='body',
            field=models.TextField(default='this is the body'),
            preserve_default=False,
        ),
    ]
