# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-02 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_carousel_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
